# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- powershell: choco install dotnetcore-sdk --pre
  displayName: Install .NET Core 3.0 preview

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell:  dotnet build -r win-x64 -c release 
  displayName: Build native Windows executable
